### PR TITLE
Added installing packages.

### PR DESCRIPTION
**Pull request by agiantwhale**

### CODE REVIEW

**Comment by EvanHahn** [comment]
@agiantwhale I can do one of four things with this:

1. merge this pull request
1. transfer ownership of the repo to you (so it'd be at `agiantwhale/caenhacks`)
1. give you admin access to this repo (so it'd stay at `EvanHahn/caenhacks`)
1. update my readme to point to `agiantwhale/caenhacks`

Does one of those sound best?

**Comment by agiantwhale** [comment]
Could you transfer the ownership? Thanks.

On Sunday, October 4, 2015, Evan Hahn <notifications@github.com> wrote:

> @agiantwhale <https://github.com/agiantwhale> I can do one of four things
> with this:
>
>    1. merge this pull request
>    2. transfer ownership of the repo to you (so it'd be at
>    agiantwhale/caenhacks)
>    3. give you admin access to this repo (so it'd stay at
>    EvanHahn/caenhacks)
>    4. update my readme to point to agiantwhale/caenhacks
>
> Does one of those sound best?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/EvanHahn/caenhacks/pull/3#issuecomment-145380463>.
>


-- 
―

[image:
DZhlJ_1wvtS23UeREYjgacK35ytjI1fX_vY469GlivTFBJ6zD4pOxClzbJYC68T6xgaHeC8tu_SjsecMsNS1HQ=s0-d-e1-ft]

Il Jae Lee | 이일재

University of Michigan, College of Engineering

BSE Computer Science

Michigan Hackers Core

iljae@umich.edu | https://ijlee.me

**Comment by EvanHahn** [comment]
Will do! Closing this PR and transferring ownership.

**Comment by EvanHahn** [comment]
@agiantwhale I got the following error:

>  agiantwhale/caenhacks already exists

Sounds like you might need to delete your repo and re-apply your patch?

**Comment by agiantwhale** [comment]
Can you try again? I renamed the repo.

**Comment by EvanHahn** [comment]
@agiantwhale Got another error:

> agiantwhale already has a repository in the EvanHahn/caenhacks network

Maybe try deleting your repo and we can try again? You can [download your patch](https://patch-diff.githubusercontent.com/raw/EvanHahn/caenhacks/pull/3.patch) and `git apply` it if you're worried about losing your changes.

**Comment by agiantwhale** [comment]
I've just deleted it.

**Comment by EvanHahn** [comment]
>  Repository transfer to agiantwhale requested

Looks good!

**Comment by agiantwhale** [comment]
Thanks, go blue!

**Comment by EvanHahn** [comment]
Thanks for taking over the repo! Let me know if you have any other problems; my email is <me@evanhahn.com>.

**Pull request closed without merging**
